<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Admin</name>
   <tag></tag>
   <elementGuidId>5482932c-3942-4a14-928e-a991abe92271</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>ul.dropit-submenu > li > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Admin')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>478b06ca-ea27-4a6e-921b-d27e0ff65704</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/admin</value>
      <webElementGuid>cf258aab-f4fc-40ac-8dfc-0c988b5874b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Admin</value>
      <webElementGuid>ad604dc9-ba04-43a5-a76d-0f9120291c28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;home&quot;]/header[@class=&quot;header&quot;]/div[@class=&quot;content&quot;]/ul[@class=&quot;header__account dropit&quot;]/li[@class=&quot;inline-display dropit-trigger dropit-open&quot;]/ul[@class=&quot;dropit-submenu&quot;]/li[1]/a[1]</value>
      <webElementGuid>a8e9f292-a972-45a4-ace7-6408ae5ceb46</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Admin')]</value>
      <webElementGuid>466ad359-50a4-4da7-9af1-543bfeda7326</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ericdicianno@gmail.com'])[1]/following::a[1]</value>
      <webElementGuid>85aeb560-1a01-43f8-86e0-93ae2983a5ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='The Hackett Group - Demo'])[1]/following::a[2]</value>
      <webElementGuid>a2324c97-07f5-49ad-89fb-12aef084947b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Profile'])[1]/preceding::a[1]</value>
      <webElementGuid>084a994d-2fbb-4100-957f-6ff2ad14501b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Data Sources'])[1]/preceding::a[2]</value>
      <webElementGuid>399a947b-0a53-4d20-b809-d8f636d9ad56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Admin']/parent::*</value>
      <webElementGuid>78c336ee-825c-4c4f-b310-2fa77ccc2714</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/admin')]</value>
      <webElementGuid>91ec53e2-bba1-49c7-be62-500d3c8fae2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/ul/li/a</value>
      <webElementGuid>47e45d84-3fa9-4a57-930f-8989c8ccb8aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/admin' and (text() = 'Admin' or . = 'Admin')]</value>
      <webElementGuid>f1659b61-ebd2-4675-aee0-f21c7cf27477</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='American Express'])[1]/following::a[2]</value>
      <webElementGuid>932f0524-3960-4147-8867-d341dbe37991</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='The Hackett Group - Testing'])[1]/following::a[2]</value>
      <webElementGuid>eb25a1ac-5d92-4e29-8b14-31b5db88d0e3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
