<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_javier.gonzalezendava.com</name>
   <tag></tag>
   <elementGuidId>72d2fbd4-c63d-4d7c-8d79-81760d1c3f62</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'javier.gonzalez@endava.com')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.dropdown-link</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>92e65f68-e24d-4ee6-b4c0-1cf4c8328a16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript://</value>
      <webElementGuid>d5628376-1afe-48cf-9a65-34f57c913d82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-link</value>
      <webElementGuid>d6d939a7-bd5c-49ea-b07f-8e4ceb288578</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
						javier.gonzalez@endava.com
						
					</value>
      <webElementGuid>d212f98c-d0a1-4ace-bb11-014f181d0dd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;home&quot;]/header[@class=&quot;header&quot;]/div[@class=&quot;content&quot;]/ul[@class=&quot;header__account dropit&quot;]/li[@class=&quot;inline-display dropit-trigger&quot;]/a[@class=&quot;dropdown-link&quot;]</value>
      <webElementGuid>98037cec-6700-4e0c-997e-37dc9a6e7505</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'javier.gonzalez@endava.com')]</value>
      <webElementGuid>89c3f98b-6b8e-47e3-87ca-6e08bcb0d597</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='The Hackett Group - Testing'])[1]/following::a[1]</value>
      <webElementGuid>0d587ab5-9172-4d1e-963b-c32769bdf482</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Digital Transformation Platform'])[1]/following::a[1]</value>
      <webElementGuid>2537d704-2848-4639-89a8-e1f43edf04f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Admin'])[1]/preceding::a[1]</value>
      <webElementGuid>7b5c9854-8ce3-496f-9bbf-03485f07158f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Profile'])[1]/preceding::a[2]</value>
      <webElementGuid>c78e96ef-5e3f-453c-ab25-78c81ef90e97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='javier.gonzalez@endava.com']/parent::*</value>
      <webElementGuid>1bc5ce16-bee7-4d1b-8654-75c8e2281c56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript://')]</value>
      <webElementGuid>6df98705-3021-4407-8b45-15a10d92c090</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a</value>
      <webElementGuid>bd70599b-8e10-4fec-b93f-2fdec20798a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript://' and (text() = '
						javier.gonzalez@endava.com
						
					' or . = '
						javier.gonzalez@endava.com
						
					')]</value>
      <webElementGuid>f820c4d4-337d-4eac-8be8-e01c1f3a0a99</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
