<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Resources</name>
   <tag></tag>
   <elementGuidId>734afc6e-12a6-4029-ba62-7e346ed814a3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#top-nav-accelerators</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='top-nav-accelerators']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1a188a82-cb71-4845-8b57-7852e98763e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>top-nav-accelerators</value>
      <webElementGuid>d148546b-5591-457f-b29b-f954f0b5b6b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>top-nav-accelerators-dropdown-trigger</value>
      <webElementGuid>e7c27810-593b-4bca-a530-defe66a9fed1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/programs?programIdentifier=47b740ec-5241-4abe-966a-2ee2c250cf81</value>
      <webElementGuid>92c42248-345e-4f04-9d6c-77b6aa6532a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
							Resources
						</value>
      <webElementGuid>6a508da9-4f48-41b2-a068-fc078efbaa85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;top-nav-accelerators&quot;)</value>
      <webElementGuid>e2764fec-1532-4ef6-901d-9fc741e446a7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='top-nav-accelerators']</value>
      <webElementGuid>876d7d72-fdb7-42b9-9e72-a2e50e3472fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Resources')]</value>
      <webElementGuid>9c3029c2-e30c-4c79-9ff3-e7cd6fbc1080</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Accelerators'])[1]/following::a[1]</value>
      <webElementGuid>735a542d-dc22-4f79-8ad4-40cf8e9f9f98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[2]/following::a[2]</value>
      <webElementGuid>d90f7583-75fb-497f-ac73-60e14d4311f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Assessments'])[1]/preceding::a[2]</value>
      <webElementGuid>6a4b0512-0add-4ddf-80bd-583f87006826</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Best Practices'])[1]/preceding::a[3]</value>
      <webElementGuid>dd670ca5-c9ef-45ad-980b-81fe6f91716b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Resources']/parent::*</value>
      <webElementGuid>fb542d02-710a-41b3-8bd7-50ad6ab5d76e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/programs?programIdentifier=47b740ec-5241-4abe-966a-2ee2c250cf81')]</value>
      <webElementGuid>32a1bb6b-1254-43ea-ab80-d7791142b109</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/ul/li[3]/a</value>
      <webElementGuid>f666128b-1445-4b99-8f8a-42a1561d3a16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'top-nav-accelerators' and @href = '/programs?programIdentifier=47b740ec-5241-4abe-966a-2ee2c250cf81' and (text() = '
							Resources
						' or . = '
							Resources
						')]</value>
      <webElementGuid>794a3745-43b5-468c-8513-a4a31aad92f4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
