<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>usernameDropdown</name>
   <tag></tag>
   <elementGuidId>72d2fbd4-c63d-4d7c-8d79-81760d1c3f62</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.dropdown-link</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(@href, 'javascript://')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>91d0807a-a43c-4214-a86f-ba4302045c35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript://</value>
      <webElementGuid>eeb18f26-ca04-448b-a47a-cd43f4da586c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-link</value>
      <webElementGuid>785a3c40-6c99-46df-a3a3-c8fa61875dd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
						javier.gonzalez@endava.com
						
					</value>
      <webElementGuid>516c3679-36cc-4510-8ed9-cc5c226273b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;home&quot;]/header[@class=&quot;header&quot;]/div[@class=&quot;content&quot;]/ul[@class=&quot;header__account dropit&quot;]/li[@class=&quot;inline-display dropit-trigger&quot;]/a[@class=&quot;dropdown-link&quot;]</value>
      <webElementGuid>d63fb324-b7bc-4615-9aa9-96bd547b8134</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'javier.gonzalez@endava.com')]</value>
      <webElementGuid>7cb942bf-3f62-4fe2-b3ad-c3308bee306b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='The Hackett Group - Testing'])[1]/following::a[1]</value>
      <webElementGuid>61bcc06e-1870-4c40-804c-bd8733f59736</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Digital Transformation Platform'])[1]/following::a[1]</value>
      <webElementGuid>99076314-a3fa-4239-94db-88f548008a44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Admin'])[1]/preceding::a[1]</value>
      <webElementGuid>b39004b1-97f9-4522-9e41-fb0307f5145e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Profile'])[1]/preceding::a[2]</value>
      <webElementGuid>a0e7ee5d-f9f6-4edb-91df-01686beb1b9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='javier.gonzalez@endava.com']/parent::*</value>
      <webElementGuid>92b64ef9-e3e3-4c33-a7b0-0b04f6d81c4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript://')]</value>
      <webElementGuid>fd7fa989-0342-4909-808a-a99de9c33a41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a</value>
      <webElementGuid>21274860-641f-4106-add3-1cbb5e0bed53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript://' and (text() = '
						javier.gonzalez@endava.com
						
					' or . = '
						javier.gonzalez@endava.com
						
					')]</value>
      <webElementGuid>c1d85472-a576-42f8-a8e0-f921efd551b9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
