<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Ceridian Demo Co</name>
   <tag></tag>
   <elementGuidId>46d3b9aa-3914-49b1-8895-c153ffc86c08</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.form-row.custom-client-container > ul > li > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e38d30ba-e0c1-4ca3-8da9-38a68235eaf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>client-id</name>
      <type>Main</type>
      <value>56e30943-de15-4f18-8a25-4deccd39cce7</value>
      <webElementGuid>df8ed224-25f7-48af-bd74-d6a896216833</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>url-name</name>
      <type>Main</type>
      <value>Ceridian-Assessment-Program</value>
      <webElementGuid>35044ae5-73c9-431e-8093-85c40e5fea7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript://</value>
      <webElementGuid>c48e569a-5708-4092-a2f4-05b504858211</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ceridian Demo Co</value>
      <webElementGuid>4c0198be-c948-4e72-8e9e-521397dfdb04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;page-wrapper&quot;]/div[@class=&quot;content signed-in&quot;]/div[@class=&quot;form-card account-form&quot;]/div[1]/div[@class=&quot;form-row custom-client-container&quot;]/ul[1]/li[1]/a[1]</value>
      <webElementGuid>44672f00-8edc-49b5-a76d-9655f4adcd60</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Ceridian Demo Co')]</value>
      <webElementGuid>9123d5bd-e394-4d53-b363-a486e18d7f1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='You have access to multiple clients. Please choose one for this session.'])[1]/following::a[28]</value>
      <webElementGuid>f8ea5258-d2b1-4327-a6d3-850f8911043f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Prospects'])[1]/following::a[28]</value>
      <webElementGuid>744b873a-f470-4632-8700-4a7c06d80f71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='The Hackett Group - Testing'])[1]/preceding::a[1]</value>
      <webElementGuid>4a4ec883-b742-4719-b309-5cbcb422c7c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Ceridian Demo Co']/parent::*</value>
      <webElementGuid>5758991b-e379-43c2-9c24-36afb8f4ce77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript://')])[3]</value>
      <webElementGuid>cfb3a99f-3bd1-4ee3-be1e-4139b555a17a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/li/a</value>
      <webElementGuid>9d6b7558-3d36-419b-9dba-783ecfbfb7fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript://' and (text() = 'Ceridian Demo Co' or . = 'Ceridian Demo Co')]</value>
      <webElementGuid>eb230581-89c5-4573-972a-9e5d7d5a9835</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
