<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Load More</name>
   <tag></tag>
   <elementGuidId>7de1961e-04b6-4d4f-8736-00dea80252e6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.data-table-footer__load-more</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div[3]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c326742a-98a3-410d-b639-54aab08e34d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript://</value>
      <webElementGuid>55eb3925-4159-4047-b753-e70cf5788042</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>data-table-footer__load-more</value>
      <webElementGuid>bd1eeefe-265d-4fbd-8599-4f42f947f287</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Load More</value>
      <webElementGuid>20e08d8f-e277-43df-a15b-ace0f581f26a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[1]/div[@class=&quot;data-table-footer&quot;]/a[@class=&quot;data-table-footer__load-more&quot;]</value>
      <webElementGuid>6843e251-7a3a-4acf-84a6-c9d59217fe60</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[3]/a</value>
      <webElementGuid>07e6e71b-6965-4bec-9ef0-33354cb966f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Load More')]</value>
      <webElementGuid>1cb29f74-8df5-4d4c-be67-4dec941b33b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Showing 25 of 2038 Best Practices'])[1]/following::a[1]</value>
      <webElementGuid>443643bf-36f4-4b6c-bdf0-9d2df4a55c95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Disburse payments to third parties electronically where legally allowable.'])[1]/following::a[1]</value>
      <webElementGuid>48f5687d-881c-46bb-8c61-5f673c1a4c6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Notice of Processing.'])[1]/preceding::a[1]</value>
      <webElementGuid>11bcca03-01c4-4cb3-9247-b16f30167db9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='www.thehackettgroup.com/privacy-statement'])[1]/preceding::a[1]</value>
      <webElementGuid>4b1b5bb6-26ad-46aa-b543-b3d8da55d73e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Load More']/parent::*</value>
      <webElementGuid>897fd866-af33-4b02-8584-1c8289de4fc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript://')])[8]</value>
      <webElementGuid>f671422c-1b8c-4fe1-8380-69014bdc943b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/a</value>
      <webElementGuid>25d34e2a-d877-48c0-ab62-ba9448f2d648</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript://' and (text() = 'Load More' or . = 'Load More')]</value>
      <webElementGuid>76d2f535-b3b3-492c-9303-88f8e4b04932</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
