<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_form-row__input</name>
   <tag></tag>
   <elementGuidId>29a0982e-3b68-40b0-94b6-b4453e6b6b11</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='password']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>118e5e5a-5b62-4f9e-aba6-74e252bb2f1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>039b6137-419a-4fca-9bcd-08e09dd65eaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-row__input</value>
      <webElementGuid>327bcf87-f491-4f61-9cac-04e51ceab3ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;account-sign-in&quot;]/div[@class=&quot;page-wrapper&quot;]/div[@class=&quot;content&quot;]/aside[@class=&quot;sidebar&quot;]/div[@class=&quot;form-card account-form&quot;]/div[@class=&quot;form-row&quot;]/input[@class=&quot;form-row__input&quot;]</value>
      <webElementGuid>2177637b-e9fe-4c80-b645-781306e0e819</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='password']</value>
      <webElementGuid>a4782a4f-14d5-455b-83f1-688d144e3ac8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>d9892dcf-9ea9-4b2d-abbb-d7803fd0dc9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password']</value>
      <webElementGuid>d19e1c43-6983-4717-8fb3-932150bd705a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
