<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Advisory</name>
   <tag></tag>
   <elementGuidId>c20be9ee-b921-4a55-8e26-8379db5325f7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Advisory')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#92ff2494-105e-4035-9003-447de2c3b17f</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>fe1dc1ff-2c4b-47ae-b0f5-1653edabc7ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>92ff2494-105e-4035-9003-447de2c3b17f</value>
      <webElementGuid>c1c6ca82-84e5-4f68-8588-8fd72099f0d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript://</value>
      <webElementGuid>965ce7ff-086d-4e94-b2e3-1eda942c0549</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Advisory</value>
      <webElementGuid>fca5e4c3-63df-4110-b569-82b4380fd8c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;92ff2494-105e-4035-9003-447de2c3b17f&quot;)</value>
      <webElementGuid>01cd7ea7-fcc5-4ccc-8fbe-62789954f3fc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='92ff2494-105e-4035-9003-447de2c3b17f']</value>
      <webElementGuid>b8260165-af04-4e03-95e5-713697003076</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='navbar']/ul[2]/li/ul/li[3]/a</value>
      <webElementGuid>dcdb7ca6-5e3f-4180-a667-d3eb8460220a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Advisory')]</value>
      <webElementGuid>76f8a2df-4064-423b-b54a-9ac9d4acb94b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ADP'])[1]/following::a[1]</value>
      <webElementGuid>c132037b-b454-46b5-b6da-7788a73881a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Admin'])[2]/following::a[2]</value>
      <webElementGuid>f5bbdb3e-9645-4853-9e0d-0367c11252d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Beroe'])[1]/preceding::a[1]</value>
      <webElementGuid>f6d8d06e-22c1-4772-975f-0fff09817587</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Oracle'])[1]/preceding::a[2]</value>
      <webElementGuid>59d37be6-3c5f-4a10-8388-bb76e6401ada</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Advisory']/parent::*</value>
      <webElementGuid>599e3b92-d140-4f42-bc57-bce3fd67b23b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript://')])[4]</value>
      <webElementGuid>474698f0-f817-421b-b18e-a730661c9eb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/ul/li[3]/a</value>
      <webElementGuid>6191223f-c7c1-403c-9cc6-550d3e413d0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = '92ff2494-105e-4035-9003-447de2c3b17f' and @href = 'javascript://' and (text() = 'Advisory' or . = 'Advisory')]</value>
      <webElementGuid>1c0f1bee-6fd3-4d43-9e82-da1f83613dc8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
